version: "3.9"
services:
  marcy-home-server:
    image: marcy-home-server:latest
    environment:
      - PSQL_HOST=postgres
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - postgres

  nginx-entrypoint:
    image: nginx
    hostname: nginx-entrypoint
    container_name: nginx-entrypoint
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./conf/conf.d:/etc/nginx/conf.d
      # - ./conf/ssl:/etc/nginx/ssl
      - ../../static:/var/www/app/static
      - ../../front:/var/www/app/front
      # - /opt/letsencrypt:/etc/letsencrypt
    networks:
      - postgres
  
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge