version: "3.9"
services:
  marcy-home-server:
    image: marcy-home-server:latest
    hostname: marcy-home-server
    environment:
      - PSQL_HOST=postgres
      - APP_URL=https://marcyhome.ru
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - "postgres"
      - "nginx-entrypoint"
    networks:
      - postgres

  nginx-entrypoint:
    build: .
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - ./nginx/service.conf:/etc/nginx/service.conf
      - ../../static:/var/www/app/static/:ro
      - ../../front:/var/www/app/front/:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=clearskyrus@gmail.com
      - LE_FQDN=www.marcyhome.ru
    networks:
      - postgres

  postgres:
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

volumes:
  postgres-data:

networks:
  postgres:
    driver: bridge