info:
  contact: {}
paths:
  /api/heartbeat:
    get:
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Heartbeat metric
      tags:
      - Metric
  /api/sensor:
    get:
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Accept and saves sensors data
      tags:
      - Sensor
swagger: "2.0"
