name: Deploy Marcy Home Service

on:
  push:
    branches: [main]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: cd deploy/prod && docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build server
        run: cd server && make build && cd ..
      - name: docker-compose
        run: cd deploy/prod && docker-compose up -d
