name: Deploy Marcy Home Service

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build server
        run: cd server && make build && cd ..
      - name: docker compose down
        run: cd deploy/prod && docker compose down && cd ../../
      - name: docker compose up
        run: cd deploy/prod && docker compose up -d && cd ../../
